version = 0.1
[default.deploy.parameters]
stack_name = "Self-Storage-Solution-rental"
resolve_s3 = true
s3_prefix = "Self-Storage-Solution-rental"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPool=\"eu-west-1_GpjXkqzK8\""
image_repositories = []
confirm_changeset = true
