AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Self-Storage Solution - Rental Service

Globals:
  Api:
    TracingEnabled: true  # Enables AWS X-Ray tracing for the API Gateway.

Parameters:
  UserPool:
    Type: String
    Description: User Pool ID produced by the Users module
   
Resources: 
  PyUtils:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: pyutils
        Description: Shared utilities for Orders service 
        ContentUri: layers/
        CompatibleRuntimes:
          - python3.9
        RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9
  RentalsTable:  # Creates the DynamoDB table with userId and orderId as the keys
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Rentals
      AttributeDefinitions:
        - AttributeName: facilityId
          AttributeType: S
        - AttributeName: unitId
          AttributeType: S
      KeySchema:  # Specifies the primary key. For Orders, the key is a composite of "userId" and "orderId".
        - AttributeName: facilityId
          KeyType: HASH
        - AttributeName: unitId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST  # user pay-per-request billing

  RentalsAPI:  # Defines the API Gateway
    Type: AWS::Serverless::Api 
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: Module3CognitoAuthorizer
        Authorizers:
          Module3CognitoAuthorizer:
            UserPoolArn:
              Fn::Sub: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}
  CreateRentalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/rent/
      Handler: book.lambda_handler
      Runtime: python3.9
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RentalsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref RentalsTable
      Events:
        BookUnit:
          Type: Api
          Properties:
            Path: /rentals/book
            Method: post
            RestApiId: !Ref RentalsAPI
Outputs:
  RentalServiceEndpoint:  # Returns the API URL
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${RentalsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  RentalsTable:
    Description: "DynamoDb Rentals Table"
    Value: !Ref RentalsTable