AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Self-Storage Solution Serverless Backend Asynchronous Pattern with EventBridge and SQS

Parameters:
  UserPool:
    Type: String
    Description: User Pool
  Service:
    Type: String
    Default: userprofile
  Stage:
    Type: String
    Default: prod

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Tracing: Active
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:20
  Api:
    TracingEnabled: true

Resources:
  UserUnitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-UnitTable
      AttributeDefinitions:
        - AttributeName: "user_id"
          AttributeType: "S"
        - AttributeName: "unit_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "user_id"
          KeyType: "HASH"
        - AttributeName: "unit_id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST

  AddUserRentUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/rent
      Handler: createRental.lambda_handler
      Runtime: python3.9
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserUnitTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UserUnitTable
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref UnitBus
            Pattern:
              source:
                - rentals-service
              detail-type:
                - rental.created

  EditUserRentalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/rent
      Handler: editStatus.lambda_handler
      Runtime: python3.9
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserUnitTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UserUnitTable
      # POWERTOOLS_SERVICE_NAME: serverless-workshop
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref UnitBus
            Pattern:
              source:
                - rentals-service
              detail-type:
                - rental.status.updated

  CancelUserRentalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/rent
      Handler: cancelRental.lambda_handler
      Runtime: python3.9
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserUnitTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UserUnitTable
      # POWERTOOLS_SERVICE_NAME: serverless-workshop
      Events:
        Trigger:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref UnitBus
            Pattern:
              source:
                - rentals-service
              detail-type:
                - rental.canceled

  UnitBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "Address-${AWS::StackName}"

  ApiGatewayEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      Path: !Join ["", ["/", !Ref "AWS::StackName", "/"]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowApiGatewayServiceToAssumeRole
            Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: EBPutEvents
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource:
                  - !GetAtt UnitBus.Arn
  
  ProfileApiGateway:
    Type: AWS::Serverless::Api
    DependsOn:
    - ApiGatewayEventBridgeRole

    Properties:
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*' # allows for logging on any resource
          HttpMethod: '*' # allows for logging on any method
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
              Location: api.yaml


  ListUserRentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/rent
      Handler: listRental.lambda_handler
      Runtime: python3.9
      Policies:
        DynamoDBReadPolicy:
          TableName: !Ref UserUnitTable
      Environment:
        Variables:
          TABLE_NAME: !Ref UserUnitTable

  ListUserRentPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref ListUserRentFunction
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ProfileApiGateway}/*/GET/rentals'

Outputs:
  UnitBus:
    Description: "Rent Unit Event Bus Output"
    Value: !Ref UnitBus
  UnitTable:
    Description: "DynamoDB User Unit Table"
    Value: !Ref UserUnitTable

  AccessLogTable:
    Description: "DynamoDB Access Log Table"
    Value: !Ref AccessLogTable

  UnitAccessNotificationTopic:
    Description: "SNS Topic for Unit Access Notifications"
    Value: !Ref UnitAccessNotificationTopic

  ProfileApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ProfileApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Prod}/"
